### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DerDreher** [stolenvw/Discord-Valheim_Bot#1]
Hi,

after playing 1-2 days with my friends the bot works not right. I have made an screenshot. 
It runs on an VPS by "Contabo" 6 Core, 16Gb RAM, 100GB NVME, Ubuntu.

![python3_fehlermeldung](https://user-images.githubusercontent.com/32548142/163946596-69615fb2-e6a6-43f0-b1e9-ab37ffd2f8af.png)

Cool Bot, hopfully u can fix it!

**Comment by stolenvw** [comment]
Do you remember if you had gotten a "bats" event when it happened?  I have not played in a while and notice they added an new event that is not in the bots database

**Comment by stolenvw** [comment]
updated bot with a possible fix.  Not somewhere i can test it so hoping it works.  Will add something to update the database with the missing event when i have time later tonight.

**Comment by DerDreher** [comment]
Thx 4 the fix. At first the bot runs, thats good :D I'll let you know if there's anything new.

**Comment by stolenvw** [comment]
File added to update the events database for the Bats event.  

Going to close this issue i believe it should be fixed, just open another issue if it happens again
