### ISSUE TITLE
timed out from A2S, retrying (60s)...

### ISSUE THREAD

**Issue by urbels** [stolenvw/Discord-Valheim_Bot#2]
Bot was working fine at first run but i had to fix permissions so it can eddit voice channel. Fixed that and now its throwing this error.

**Comment by stolenvw** [comment]
If you have -public=0 in your start script for the valheim server this will happen, it uses the steam query port to see if the server is online. Other cause is wrong ip port set in the config

**Comment by urbels** [comment]
nvm my bad, I changed from query port to game port
