### ISSUE TITLE
"/explored" runs in to an error

### ISSUE THREAD

**Issue by DerDreher** [stolenvw/Discord-Valheim_Bot#3]
Ho stolenvw,

i have double check the path and the pemission to the world file. But my bot gives me an error. My Path would be, for example:

worldfile = '/home/steam/.config/unity3d/IronGate/Valheim/Greyhoundworld/worlds_local/Greyhoundworld.db.old'
[valheimbot.log](https://github.com/stolenvw/Discord-Valheim_Bot/files/10209743/valheimbot.log)

**Comment by stolenvw** [comment]
/explored command dont use the worldfile.

do you have the plocinfo table in your mysql database
and PLOCINFO = True in the config.py

**Comment by DerDreher** [comment]
Ah ok. 
The "plocinfo table" is in my database and the PLOCINFO = True in the config.py.

/deaths also brings an error for me:
2022-12-12 17:15:18 - ERROR - botcmds.maincmd: An error occurred! User: 🅶 I|I Rambo_GT, Command 'deaths' raised an exception: TypeError: can only concatenate str (not "int") to str

**Comment by stolenvw** [comment]
ok will look into deaths later when i get home, that one is also not working for me.

explored is working for me so not sure what is up with that one.  does your plocinfo table have any data in it yet?

**Comment by DerDreher** [comment]
My first attempts still contained old data. After your answer I have reloaded the DB. Currently it is empty.

**Comment by stolenvw** [comment]
deaths cmd should be fixed now

**Comment by DerDreher** [comment]
looks good

**Comment by DerDreher** [comment]
ok now i have some Data in the plocinfo Table. But /explored continues to give me an error. In the database under "locations" in each row is (NULL) is that correct?

**Comment by stolenvw** [comment]
should just be one row that has a number in "locations",  its total locations server has placed, I believe the vlaheim server only gives that info right after it has started. So bot needs to be running when server starts to get that info.  Its been awhile since i have really looked at the Valheim server log file.

**Comment by stolenvw** [comment]
you can make a row with a number in that column and the other 2 as null for now and /explore should work, then when you restart the server with the bot already running it should update it, or just restart the server

**Comment by DerDreher** [comment]
Hey stolenvw,

yesterday i created a line with the values id, locations, zone durations -> 72, 1, 0, 0. And yes, now there is no error message. Instead it shows in Discord:

World Explored Stats
Total Locations
1
Locations Explored
71
Percent of World Explored
7100.00%

Is it possible that the debug channel in Discord doesn't show anything anymore either? There is something in the logs, but not in the DC. The version number of the Valheimserver doesn't seem to be tracked anymore. I think it's a good idea to have a look at the server logs :)

I think your bot is great. Keep up the good work .

**Comment by stolenvw** [comment]
Set `USEDEBUGCHAN = False` to true in the config should send stuff to the discord debug Chan again, need to restart bot after change.  With bot running restart the valheim server it should get the server version.  I tested that part with both of my servers and it worked for me. I might see if there is a different way to get the version number besides reading from the log file.

**Comment by stolenvw** [comment]
Okay got a way to get server version info from a2s (steam query), will add the changes after work to have it query the server every 30min for version info.

**Comment by DerDreher** [comment]
hey stolenvw,

I just wanted to inform you that the situation has changed after a server restart. It has been running for about half a year. Now the bot works. But there is still one thing that stands out. One of our players has a name with a space. This is apparently not recognized by your script.

Greetings and ne nice pre-Christmas season :)

**Comment by stolenvw** [comment]
okay, will look at regular expression's to get them to see names with a space in them

**Comment by stolenvw** [comment]
That should fix names with spaces :)
